import { Lead, DocumentItem } from './types';

export const DEFAULT_DOCUMENTS: DocumentItem[] = [
  { id: 'd1', name: 'RG ou CNH', status: 'Pendente de Solicitar', type: 'obrigatório' },
  { id: 'd2', name: 'Comprovante de Residência', status: 'Pendente de Solicitar', type: 'obrigatório' },
  { id: 'd3', name: 'Contrato de Compra e Venda', status: 'Pendente de Solicitar', type: 'obrigatório' },
  { id: 'd4', name: 'Briefing', status: 'Pendente de Solicitar', type: 'obrigatório' },
  { id: 'd5', name: 'Extrato de Pagamentos', status: 'Pendente de Solicitar', type: 'obrigatório' },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: '1',
    name: 'João Silva',
    profession: 'Engenheiro',
    phone: '11999999999',
    city: 'São Paulo',
    state: 'SP',
    valuePaid: 150000,
    propertyType: 'Imóvel Pronto',
    brokerage: 5000,
    delays: 3,
    signedDistrato: 'Não',
    notes: 'Interessado em distrato rápido.',
    proposal: 120000,
    status: 'Novo',
    email: 'joao@example.com',
    address: 'Av. Paulista, 1000',
    neighborhood: 'Bela Vista',
    zipCode: '01310-100',
    rg: '12.345.678-9',
    cpf: '123.456.789-00',
    createdAt: '2026-01-15T10:00:00Z'
  },
  {
    id: '2',
    name: 'Maria Oliveira',
    profession: 'Médica',
    phone: '21988888888',
    city: 'Rio de Janeiro',
    state: 'RJ',
    valuePaid: 300000,
    propertyType: 'Planta',
    brokerage: 10000,
    delays: 0,
    signedDistrato: 'Sim',
    notes: 'Já assinou mas quer revisar valores.',
    proposal: 250000,
    status: 'Qualificação',
    email: 'maria@example.com',
    address: 'Rua das Flores, 50',
    neighborhood: 'Jardim Botânico',
    zipCode: '22460-000',
    rg: '98.765.432-1',
    cpf: '987.654.321-11',
    createdAt: '2026-02-10T14:30:00Z'
  },
  {
    id: '3',
    name: 'Carlos Santos',
    profession: 'Advogado',
    phone: '31977777777',
    city: 'Belo Horizonte',
    state: 'MG',
    valuePaid: 200000,
    propertyType: 'Imóvel Pronto',
    brokerage: 8000,
    delays: 2,
    signedDistrato: 'Sim',
    notes: 'Contrato já assinado e em fase de cobrança.',
    proposal: 180000,
    status: 'Assinado',
    email: 'carlos@example.com',
    createdAt: '2026-02-20T09:15:00Z',
    contract: {
      percentage: 20,
      format: 'Parcelado',
      value: 1200,
      paymentMethod: 'Boleto Bancário',
      installments: 12,
      dueDate: 10,
      firstInstallmentDate: '2026-03-10',
      generateBilling: true
    },
    documentData: {
      code: 'C68',
      documents: [
        ...DEFAULT_DOCUMENTS,
        { id: 'd6', name: 'Matrícula', status: 'Recebido', type: 'eventual' }
      ],
      observations: [
        { id: 'o1', author: 'Gabriel Igreja', text: 'Ainda vou solicitar RG e Residência', timestamp: '2026-03-04T11:36:00Z' },
        { id: 'o2', author: 'João Perdigão', text: 'Loteadora respondeu nosso primeiro e-mail enviado automaticamente pedindo a procuração para seguir com o atendimento e após o envio da procuração em 09/03 não responderam mais.', timestamp: '2026-03-11T12:20:00Z' }
      ],
      emailSent: true,
      notificationSent: false
    }
  },
  {
    id: '4',
    name: 'Ana Lima',
    profession: 'Arquiteta',
    phone: '41966666666',
    city: 'Curitiba',
    state: 'PR',
    valuePaid: 500000,
    propertyType: 'Planta',
    brokerage: 15000,
    delays: 0,
    signedDistrato: 'Sim',
    notes: 'Lead de alto valor.',
    proposal: 450000,
    status: 'Assinado',
    email: 'ana@example.com',
    createdAt: '2026-03-05T16:45:00Z',
    contract: {
      percentage: 25,
      format: 'Parcelado',
      value: 2500,
      paymentMethod: 'PIX',
      installments: 1,
      dueDate: 5,
      firstInstallmentDate: '2026-03-15',
      generateBilling: true
    },
    documentData: {
      code: 'C67',
      documents: [
        { id: 'd1', name: 'RG ou CNH', status: 'Recebido', type: 'obrigatório' },
        { id: 'd2', name: 'Comprovante de Residência', status: 'Recebido', type: 'obrigatório' },
        { id: 'd3', name: 'Contrato de Compra e Venda', status: 'Recebido', type: 'obrigatório' },
        { id: 'd4', name: 'Briefing', status: 'Recebido', type: 'obrigatório' },
        { id: 'd5', name: 'Extrato de Pagamentos', status: 'Recebido', type: 'obrigatório' },
        { id: 'd6', name: 'Matrícula', status: 'Recebido', type: 'eventual' },
        { id: 'd7', name: 'Certidão de Casamento', status: 'Recebido', type: 'eventual' },
        { id: 'd8', name: 'Pacto Antenupcial', status: 'Recebido', type: 'eventual' },
        { id: 'd9', name: 'Procuração', status: 'Recebido', type: 'eventual' },
      ],
      observations: [],
      emailSent: true,
      notificationSent: true
    }
  },
  {
    id: '5',
    name: 'Ricardo Souza',
    profession: 'Empresário',
    phone: '11955555555',
    city: 'São Bernardo',
    state: 'SP',
    valuePaid: 80000,
    propertyType: 'Planta',
    brokerage: 4000,
    delays: 5,
    signedDistrato: 'Não',
    notes: 'Churn por falta de pagamento.',
    proposal: 0,
    status: 'Churn',
    email: 'ricardo@example.com',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    financialRecord: {
      multaRescisoriaDevida: 12000,
      dataChurn: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      statusExecucao: 'Aguardando'
    }
  },
  {
    id: '6',
    name: 'Juliana Mendes',
    profession: 'Designer',
    phone: '11944444444',
    city: 'Santo André',
    state: 'SP',
    valuePaid: 120000,
    propertyType: 'Imóvel Pronto',
    brokerage: 6000,
    delays: 0,
    signedDistrato: 'Sim',
    notes: 'Processo ganho em primeira instância.',
    proposal: 100000,
    status: 'Assinado',
    email: 'juliana@example.com',
    createdAt: '2026-01-20T11:00:00Z',
    financialRecord: {
      tipoResultado: 'sentenca_procedente',
      valorCondenacao: 85000,
      valorRestituicao: 70000,
      honorariosSucumbenciaisContratuais: 15000,
      dataPagamento: '2026-03-15',
      anexoSentenca: 'sentenca_procedente_001.pdf'
    }
  },
  {
    id: '7',
    name: 'Marcos Roberto',
    profession: 'Professor',
    phone: '11933333333',
    city: 'Osasco',
    state: 'SP',
    valuePaid: 50000,
    propertyType: 'Planta',
    brokerage: 2500,
    delays: 0,
    signedDistrato: 'Sim',
    notes: 'Acordo extrajudicial.',
    proposal: 45000,
    status: 'Assinado',
    email: 'marcos@example.com',
    createdAt: '2026-02-05T09:00:00Z',
    financialRecord: {
      tipoResultado: 'acordo',
      valorAcordo: 42000,
      valorHonorarios: 8400,
      dataPagamento: '2026-03-10'
    }
  },
  {
    id: '8',
    name: 'Fabiana Costa',
    profession: 'Enfermeira',
    phone: '11922222222',
    city: 'Guarulhos',
    state: 'SP',
    valuePaid: 30000,
    propertyType: 'Planta',
    brokerage: 1500,
    delays: 0,
    signedDistrato: 'Sim',
    notes: 'Tese rejeitada pelo juiz.',
    proposal: 25000,
    status: 'Assinado',
    email: 'fabiana@example.com',
    createdAt: '2026-02-15T10:00:00Z',
    financialRecord: {
      tipoResultado: 'improcedente',
      motivoImprocedencia: 'Tese Rejeitada',
      anexoSentenca: 'sentenca_improcedente_002.pdf'
    }
  }
];

export const KANBAN_COLUMNS = [
  'Novo',
  'Qualificação',
  'Follow-up',
  'Reunião',
  'Stand-by',
  'Assinado',
  'Churn',
  'Recusado',
  'Desqualificado',
  'Recuperação'
];
